### ISSUE TITLE
Add cabal-install-3.4.0.0

### ISSUE THREAD

**Issue by RyanGlScott** [Mistuke/CabalChoco#3]
See https://downloads.haskell.org/~cabal/cabal-install-3.4.0.0/cabal-install-3.4.0.0-x86_64-windows.zip for the Windows bindist.

**Comment by Mistuke** [comment]
Thanks for the heads-up, was waiting for the release. I will add them after work today.

**Comment by Mistuke** [comment]
Hmm that release is kinda broken, the file inside has no extension so it won't run.

I can work around it but hesitant to do so if they are planning to fix it since that changes the sha256 and breaks the package. So will need to know if this is final.

**Comment by RyanGlScott** [comment]
> Hmm that release is kinda broken, the file inside has no extension so it won't run.

Interesting! Is this a known issue, @phadej?

**Comment by phadej** [comment]
I don't remember changing anything in [release.py](https://github.com/haskell/cabal/blob/master/release.py)

Also previous (release candidates) zip in http://oleg.fi/cabal-install-3.4.0.0-rc4/ has just "cabal" (not cabal.exe). I wasn't aware that is a problem.

**Comment by Mistuke** [comment]
> Also previous (release candidates) zip in http://oleg.fi/cabal-install-3.4.0.0-rc4/ has just "cabal" (not cabal.exe). I wasn't aware that is a problem.

The previous RC releases on chocolatey are ones I built myself. It's not a problem for the OS, which just checks the first two bytes of the file. But it's a problem for the shell (i.e. explorer can't run this, but granted, cabal is commandline anyway) and it's a problem for tools like chocolatey which filters executables based on extensions.

As I said not a problem for me, I can add a workaround (namely calling `install-binfile` explicitly), but it's highly unusual not to have an extension for a Windows program.  I'm not sure what other tooling breaks.

**Comment by phadej** [comment]
Yes, I'm not arguing we shouldn't fix `release.py`. But I'd say the proper place to discuss that further is Cabal's issue tracker.

**Comment by Mistuke** [comment]
I created https://github.com/haskell/cabal/issues/7298

**Comment by Mistuke** [comment]
Done, https://chocolatey.org/packages/cabal/3.4.0.0

Will take an hour or two to go through moderation. GHC 9.0 should follow shortly. (package was unable to be submitted until cabal was available)
